organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - gitea_admin
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/nwsmonster/homelab
      mirror: true
    hook: true
